### ISSUE TITLE
Jenkins broken

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [EssentialsX/Website#10]
https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/Essentials/target/
:

Error 502 Ray ID: *** 2020-02-20 06:55:11 UTC
Bad gateway

**Comment by pop4959** [comment]
We're aware. Please use <https://old.ci.akpmakes.tech/job/EssentialsX/> for now.

**Comment by md678685** [comment]
The build server and downloads page are back online.
