### ISSUE TITLE
[Proposal] Use Tweemoji for Emojis in download page

### ISSUE THREAD

**Issue by Andre601** [EssentialsX/Website#32]
I suggest to use Tweemoji in the download page to replace the current emojis used there. Reasons:

- Free and open source
- Same design across multiple platforms (More on that below)

A small but still present disadvantage of using the raw unicode emojis is, that they will look different depending on what OS you use.
On Windows will they have a different, kind-of dated look while on android the ✅ may have a gradient-ish style to it.
With Tweemoji would it have the same simple style across all platforms.

This is obviously a rather minor thing, so no worries if you want to keep it for a very late change (or don't want to change at all.)

**Comment by mdcfe** [comment]
There's not really any reason to include an entire new emoji font in the website. We may replace some usage of emoji with icons in the future, but there's currently no reason for us to switch.
