### ISSUE TITLE
"MOSS" actually called "M.O.S.S."?

### ISSUE THREAD

**Issue by Andre601** [EssentialsX/Website#33]
Shouldn't the Discord Server in the community page be called "M.O.S.S." since that's the actual name of the Discord itself?

In that case would I suggest to.
A) Change name to M.O.S.S. and
B) Change the text in the Discord field to `EssentialsX is part of the <b>M.O.S.S. Discord Server</b>`

**Comment by mdcfe** [comment]
`MOSS` is the preferred acronym on the EssentialsX website for the sake of readability.
