### ISSUE TITLE
Getting script 404 on download page, no downloads shown.

### ISSUE THREAD

**Issue by sonicer105** [EssentialsX/Website#93]
Getting a 404 on https://essentialsx.net/_saber/js/page--downloads-vue.f8e98257.js

![image](https://github.com/EssentialsX/Website/assets/6855083/9bb87138-7705-470a-9ee5-84695646603b)

I have tested multiple computers with multiple browsers and multiple different network configurations and cannot load the page.

**Comment by mdcfe** [comment]
I've rebuilt the website and cleared the cache. Would you be able to test the website again on your end?

**Comment by sonicer105** [comment]
It does appear to be working now. Thanks!
